# Generated by Django 5.2 on 2025-06-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_product_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_fruit",
            field=models.BooleanField(default=False),
        ),
    ]
